"""empty message

Revision ID: 1ea3121d6813
Revises: 
Create Date: 2025-03-08 11:34:34.385427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea3121d6813'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=True),
    sa.Column('sobre_mim', sa.String(length=140), nullable=True),
    sa.Column('visto_ultimo', sa.DateTime(), nullable=True),
    sa.Column('tempo_ultima_mensagem_lida', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('corpo', sa.String(length=140), nullable=False),
    sa.Column('tempo', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mensagem_destinatario_id'), ['destinatario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensagem_remetente_id'), ['remetente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mensagem_tempo'), ['tempo'], unique=False)

    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacao_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacao_tempo'), ['tempo'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacao_user_id'), ['user_id'], unique=False)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpo', sa.String(length=280), nullable=False),
    sa.Column('tempo', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_tempo'), ['tempo'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    op.create_table('seguidores',
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.Column('seguindo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguidor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seguindo_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('seguidor_id', 'seguindo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidores')
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_tempo'))

    op.drop_table('post')
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacao_user_id'))
        batch_op.drop_index(batch_op.f('ix_notificacao_tempo'))
        batch_op.drop_index(batch_op.f('ix_notificacao_nome'))

    op.drop_table('notificacao')
    with op.batch_alter_table('mensagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mensagem_tempo'))
        batch_op.drop_index(batch_op.f('ix_mensagem_remetente_id'))
        batch_op.drop_index(batch_op.f('ix_mensagem_destinatario_id'))

    op.drop_table('mensagem')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
