"""empty message

Revision ID: b84e148327bb
Revises: d2d81f0fc116
Create Date: 2025-02-27 11:42:58.553179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b84e148327bb'
down_revision = 'd2d81f0fc116'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.Column('seguindo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seguidor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seguindo_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('seguidor_id', 'seguindo_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidores')
    # ### end Alembic commands ###
