"""adicionado novos campos em user

Revision ID: d2d81f0fc116
Revises: 9867e26a49d9
Create Date: 2025-02-26 08:37:26.426092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2d81f0fc116'
down_revision = '9867e26a49d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobre_mim', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('visto_ultimo', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('visto_ultimo')
        batch_op.drop_column('sobre_mim')

    # ### end Alembic commands ###
